### ISSUE TITLE
[Feature] benchmark / smoke-test scripts: planning/structure

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-workflows#9]
**Is your feature request related to a problem? Please describe.**
We'd like to have Python scripts that execute some key workflows discussed in the developer meeting on 14/09/2023.
These are
* cell detection brainglobe/brainglobe-scripts#5 
* image registration from sample to atlas space brainglobe/brainglobe-scripts#4 
* transforming data from sample to atlas space brainglobe/brainglobe-scripts#3 
* accessing atlas data through the `bg-atlasapi` brainglobe/brainglobe-scripts#2 
* [possibly others, and combinations of these, but let's focus on these first?]

We can farm out the writing of each of these scripts to a separate issue, once we've agreed on what requirements we have for them.

**Describe the solution you'd like**
I propose the requirements are (based on dev meeting discussion)
* Simple, legible python scripts
* Can be run on **both** big, real-life data and small test data
* Maybe build in a way so parts of the code can be re-used within a jupyter notebook (for teaching materials/tutorials?)

The main purpose of these scripts is benchmarking and smoke-testing (on large data).
It would be nice if they would be re-usable in teaching materials/docs/tutorials.

**Naively suggested structure**
* Keep the scripts in a `benchmark-workflows` folder in this repo.
* have this as an optional dependency for this package
* Use environmental variable to pass the path to the test data
* Code would look something like:
```python
# pseudo-code approximating Python
# function names made up
import os
from pathlib import Path

def example_workflow():
	input_data_path = Path(os.environ("BENCHMARK_DATA"))
	assert input_data_path.exists()
	input_data = read(input_data_path)
	preprocess_data = process(input_data) # if required
	results = run_main_tool(prepocessed_data)
	save(results)

if __name__ == "__main__":
	example_workflow()
```
* maybe [`%load file.py` can be used to have `example_workflow` in a jupyter notebook](https://stackoverflow.com/questions/21034373/how-to-load-edit-run-save-text-files-py-into-an-ipython-notebook-cell)
 
**Describe alternatives you've considered**
* Maybe we should have an entirely different `brainglobe-benchmarks` or `brainglobe-scripts` repo instead? (As much as I'd like to reduce the number of repos!) - we can still do this at a later point, I guess (with a bit more effort...)

**Comment by sfmig** [comment]
Discussion of workflows general structure with @alessandrofelder 

- we want to define workflows that can fetch data from GIN and also locally
- a workflow needs an input configuration which contains the required parameters
- the input config is set to some default values, but can be customised via an environment variable
- so the input configuration is defined:
  - either via a default, if no environment variable is defined
  - via an environment variable that points to a json file with the required parameters. We are undecided on where this json file should live: hardcoded (in a constant or in a local dict variable), or in a json in the repo, or on GIN

**Comment by sfmig** [comment]
Why an environment variable to point to the config file?

- avoid writing argparse code
- confusing to add an additional CLI (on top of the existing ones for cellfinder, brainreg)
- CLI is most useful for users, whereas we are aiming this to be mostly non-user facing code, that can run independently in a dev environment without much setup but that developers can also customise to work locally
- if we go CLI, we would have to hardcode CLI arguments into our calls to GH runners

**Comment by alessandrofelder** [comment]
Small thought experiment trying to predict ~what the GH actions yaml would look like depending on whether we make the config file an optional CLI argument or an environmental variable - having an optional CLI argument makes the job slightly shortly and more explicit, I think.

This is one of our main use cases, so I am classing this as a pro for the optional CLI argument.
```
jobs:
  if: is_local # !!!! not actual GH actions syntax !!!
  example_matrix:
    strategy:
      matrix:
        brainreg-config: 
        [
            /media/hard-drive/large-data-1/config.json,
            ~/large-data-2/config.json
        ]
  brainreg_large_data_job:
    runs-on: ubuntu-latest
    env:
      BRAINREG_CONFIG_PATH: {{ $brainreg-config }} 
    steps:
      - name: "Run brainreg workflow"
        run: python brainreg/brainreg-workflow.py
```


```
jobs:
  if: is_local
  example_matrix:
    strategy:
      matrix:
        brainreg-config: 
        [
            /media/hard-drive/large-data-1/config.json,
            ~/large-data-2/config.json
        ]
  brainreg_large_data_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Run brainreg workflow"
        run: python brainreg/brainreg-workflow.py --config {{ $brainreg-config}} 
```
